remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

title: isochrone-map-osmnx
description: A geospatial project that utilizes OSMnx to create and visualize isochrone maps.

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Read me
    link: ./index.html
  - name: Jupyter Notebook 
    link: ./isochrone_map1