remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

title: 7020-customer-segmentation
description: An unspervised learning, customer segmentation project.

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Read me
    link: ./index.html
  - name: R markdown
    link: ./custseg-7022