remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

title: r-kaggle-survey-2022
description: An analysis of kaggle 2022 survey data

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Read me
    link: ./index.html
  - name: R markdown
    link: ./finalproj.html