remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

title: 7020-customer-segmentation
description: An unspervised learning, customer segmentation project.

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Read me
    link: ./index.html
  - name: R markdown
    link: ./custseg-7020
  - name: Data Viz Report
    link: https://drive.google.com/file/d/11wJvhyFXu1C0P_FbTcMowWgHiuZdqjPI/view?usp=sharing
  - name: <%= link_to “https://drive.google.com/file/d/11wJvhyFXu1C0P_FbTcMowWgHiuZdqjPI/view?usp=sharing”, foo_path, :target => ‘_blank’ %>  