remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

title: creating-isochrone-map
description: isochrone map tutorial using OSMnx

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Readme
    link: ./index.html
  - name: Jupyter Notebook 
    link: ./isochrone_map1